(function(){
  var deferredInstallPrompt=null,installBtn=document.getElementById('install-app-btn'),updateBar=document.getElementById('pwa-update-bar'),updateBtn=document.getElementById('pwa-update-btn'),offlineBar=document.getElementById('pwa-offline-bar'),offlineTimer=null,reloading=false;
  function isStandalone(){return window.matchMedia&&window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;}
  function setOfflineState(){if(offlineBar){clearTimeout(offlineTimer);if(!navigator.onLine){offlineBar.classList.add('show');offlineTimer=setTimeout(function(){offlineBar.classList.remove('show');},5000);}else offlineBar.classList.remove('show');}if(window.refreshConnectionStatus)window.refreshConnectionStatus();}
  window.addEventListener('online',setOfflineState);window.addEventListener('offline',setOfflineState);setOfflineState();
  window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredInstallPrompt=e;if(installBtn&&!isStandalone())installBtn.classList.add('show');});
  if(installBtn)installBtn.addEventListener('click',async function(){if(!deferredInstallPrompt)return;deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice;}catch(e){}deferredInstallPrompt=null;installBtn.classList.remove('show');});
  window.addEventListener('appinstalled',function(){deferredInstallPrompt=null;if(installBtn)installBtn.classList.remove('show');var h=document.getElementById('pwa-install-help');if(h)h.classList.add('hidden');});
  function showInstallHelp(){var h=document.getElementById('pwa-install-help'),t=document.getElementById('pwa-install-help-text');if(!h)return;if(t)t.textContent=/iPhone|iPad|iPod/i.test(navigator.userAgent)?'In Safari, tap Share, then Add to Home Screen.':'If Chrome does not show Install app, open the browser menu (⋮) and choose Add to home screen.';h.classList.remove('hidden');}
  var fi=document.getElementById('pwa-install-action'),fc=document.getElementById('pwa-install-close');
  if(fi)fi.addEventListener('click',async function(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice;}catch(e){}deferredInstallPrompt=null;if(installBtn)installBtn.classList.remove('show');}else showInstallHelp();});
  if(fc)fc.addEventListener('click',function(){var h=document.getElementById('pwa-install-help');if(h)h.classList.add('hidden');});
  function showUpdate(reg){if(!updateBar)return;updateBar.classList.add('show');if(updateBtn)updateBtn.onclick=function(){if(reg&&reg.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});};}
  if('serviceWorker' in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('./service-worker.js',{scope:'./'}).then(function(reg){if(reg.waiting)showUpdate(reg);reg.addEventListener('updatefound',function(){var w=reg.installing;if(!w)return;w.addEventListener('statechange',function(){if(w.state==='installed'&&navigator.serviceWorker.controller)showUpdate(reg);});});reg.update().catch(function(){});setInterval(function(){reg.update().catch(function(){});},120000);document.addEventListener('visibilitychange',function(){if(!document.hidden)reg.update().catch(function(){});});}).catch(function(){});});navigator.serviceWorker.addEventListener('message',function(e){if(e.data&&e.data.type==='UPDATE_READY'&&navigator.serviceWorker.controller)document.documentElement.setAttribute('data-update-ready','true');});navigator.serviceWorker.addEventListener('controllerchange',function(){if(reloading)return;reloading=true;window.location.reload();});}
  var backExitDeadline=0,backTimer=null;function armBackExit(){backExitDeadline=Date.now()+5000;if(window.showSuccess)window.showSuccess('Press again to exit.');clearTimeout(backTimer);backTimer=setTimeout(function(){backExitDeadline=0;},5000);history.pushState({farmLedger:true},document.title,location.href);}
  if(window.history&&window.history.pushState){history.replaceState({farmLedger:true},document.title,location.href);history.pushState({farmLedger:true},document.title,location.href);window.addEventListener('popstate',function(){var appVisible=document.getElementById('app-view')&&!document.getElementById('app-view').classList.contains('hidden'),viewer=document.getElementById('image-viewer'),help=document.getElementById('pwa-install-help');if(!appVisible)return;if(viewer&&viewer.style.display==='flex'){viewer.style.display='none';history.pushState({farmLedger:true},document.title,location.href);return;}if(help&&!help.classList.contains('hidden')){help.classList.add('hidden');history.pushState({farmLedger:true},document.title,location.href);return;}if(Date.now()<=backExitDeadline){backExitDeadline=0;clearTimeout(backTimer);history.go(-1);return;}armBackExit();});}
})();
